### ISSUE TITLE
New comand Modbus ON/OFF inverter DEYE

### ISSUE THREAD

**Issue by Antoled** [slipx06/Sunsynk-Home-Assistant-Dash#31]
I integrated modbus commands to remotely send the inverter ON/OFF (like acting on the button at the bottom) the consumption becomes extremely low. Leave the sections to integrate for those who need it.

  

 ```
- platform: modbus_controller            # 020 Switch ON/OFF INVERTER
    use_write_multiple: true
    modbus_controller_id: inverter
    name: "${friendly_name} Switch ON/OFF inverter" 
    id: inverter_esphome_toggle_Switch_ON_OFF_INVERTER
    address: 20
    value_type: U_WORD
    optionsmap:
      "OFF": 2
      "ON": 1
```

 ```
 - platform: modbus_controller            # 020 Switch ON/OFF INVERTER
    use_write_multiple: true
    inverted: True
    modbus_controller_id: inverter
    name: "${friendly_name} Switch ON/OFF " 
    id: inverter_esphome_toggle_Switch_ON_OFF
    register_type: holding
    address: 20
    bitmask: 2
    icon: "mdi:toggle-switch"

```
