### ISSUE TITLE
Mismatch Between Modbus Register Address and Comment

### ISSUE THREAD

**Issue by huzii7** [slipx06/Sunsynk-Home-Assistant-Dash#36]
There is a potential mismatch between the Modbus register address and the comment in the following YAML configuration:  ESPHome-1P-Sunsynk-Deye.yaml

```
  - platform: modbus_controller            # 150 Grid Voltage
    modbus_controller_id: inverter
    name: "${friendly_name} Grid Voltage"
    id: inverter_esphome_grid_voltage
    register_type: holding
    address: 152
    unit_of_measurement: "V"
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement
    filters:
      - multiply: 0.1
    value_type: U_WORD 
```
The comment suggests register 150 (# 150 Grid Voltage).
The actual address value is 152.
